# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PMove
email: contato@mrp3.com.br
description: "Documentação das APIs de integração do PMove"
url: "http://pmove.github.io" # the base hostname & protocol for your site
github_username: pmove

# Documentation system variables
default_categories:
  - 'Planejamento'
  - 'Rota'
  - 'Produto'
  - 'Equipe'
  - 'Veículo'
  - 'Usuário'
  - 'Roteirizador'
  - 'Suporte'

# Google cse -> read the README.md for learn more.
# gcse: 006270711061491111331:vsivtajjjh0

# Conversion
markdown: rdiscount

# Outputting
relative_permalinks: false
permalink:           /:path
timezone:            Asia/Jakarta

# Markdown Processors
kramdown:
   input: GFM

# Exclude file
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - bower_components
  - node_modules
  - vendor
